"""add dish sort_order

Revision ID: f9af017f5530
Revises: 9e81af4b0d50
Create Date: 2026-08-15 04:02:10.584241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9af017f5530'
down_revision: Union[str, None] = '9e81af4b0d50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dishes', sa.Column('sort_order', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('dishes', 'sort_order', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dishes', 'sort_order')
    # ### end Alembic commands ###
