SEED_CATEGORIES = [
    {"id": "pizza", "name": "Пицца", "sort_order": 1},
    {"id": "burgers", "name": "Бургеры", "sort_order": 2},
    {"id": "sandwiches", "name": "Сэндвичи", "sort_order": 3},
    {"id": "hotdogs", "name": "Хот-доги", "sort_order": 4},
    {"id": "snacks", "name": "Закуски", "sort_order": 5},
    {"id": "sauces", "name": "Соусы", "sort_order": 6},
]

SEED_DISHES = [
    {
        "id": "pizza-devila",
        "category_id": "pizza",
        "name": "Пицца Дьявола",
        "description": "Острая пицца с пикантной пепперони и перцем халапеньо",
        "composition": "Томатный соус, моцарелла, пепперони, халапеньо, чили",
        "weight": "450 г",
        "price": 560,
    },
    {
        "id": "pizza-pepperoni",
        "category_id": "pizza",
        "name": "Пицца Пепперони",
        "description": "Классика с хрустящей пепперони и сыром",
        "composition": "Томатный соус, моцарелла, пепперони",
        "weight": "450 г",
        "price": 540,
    },
    {
        "id": "pizza-cheese",
        "category_id": "pizza",
        "name": "Пицца Сырная",
        "description": "Четыре сорта сыра для настоящих гурманов",
        "composition": "Моцарелла, чеддер, пармезан, дор блю, сливочный соус",
        "weight": "430 г",
        "price": 520,
    },
    {
        "id": "pizza-village",
        "category_id": "pizza",
        "name": "Пицца Деревенская",
        "description": "Сытная пицца с беконом, картофелем и грибами",
        "composition": "Томатный соус, моцарелла, бекон, картофель, грибы, лук",
        "weight": "480 г",
        "price": 570,
    },
    {
        "id": "pizza-mushroom",
        "category_id": "pizza",
        "name": "Пицца Грибная",
        "description": "Ароматная пицца с лесными грибами и сливочным соусом",
        "composition": "Сливочный соус, моцарелла, шампиньоны, лесные грибы",
        "weight": "440 г",
        "price": 530,
    },
    {
        "id": "pizza-chicken-mushroom",
        "category_id": "pizza",
        "name": "Пицца Курица/Грибы",
        "description": "Нежная курица с грибами под сырной шапкой",
        "composition": "Сливочный соус, моцарелла, курица, шампиньоны",
        "weight": "460 г",
        "price": 550,
    },
    {
        "id": "pizza-meat",
        "category_id": "pizza",
        "name": "Пицца Мясная",
        "description": "Три вида мяса для настоящего похода",
        "composition": "Томатный соус, моцарелла, говядина, ветчина, бекон",
        "weight": "500 г",
        "price": 610,
    },
    {
        "id": "burger-smash",
        "category_id": "burgers",
        "name": "Смэш Бургер",
        "description": "Сочная смэш-котлета с хрустящей корочкой",
        "composition": "Булка бриошь, говяжья котлета, чеддер, соус, маринованные огурцы",
        "weight": "280 г",
        "price": 390,
    },
    {
        "id": "sandwich-beef",
        "category_id": "sandwiches",
        "name": "Сэндвич с говядиной",
        "description": "Сытный сэндвич с сочной говядиной",
        "composition": "Тостовый хлеб, говядина, сыр, соус, свежие овощи",
        "weight": "310 г",
        "price": 380,
    },
    {
        "id": "sandwich-cheesesteak",
        "category_id": "sandwiches",
        "name": "Сэндвич Чизстейк",
        "description": "Тонко нарезанная говядина с плавленым сыром",
        "composition": "Багет, говядина, сырный соус, лук, перец",
        "weight": "320 г",
        "price": 410,
    },
    {
        "id": "cheesesteak-roll",
        "category_id": "sandwiches",
        "name": "Чизстейк Ролл",
        "description": "Ролл с говядиной и сырным соусом",
        "composition": "Лаваш, говядина, сырный соус, лук, перец",
        "weight": "300 г",
        "price": 400,
    },
    {
        "id": "hotdog-mexican",
        "category_id": "hotdogs",
        "name": "Хот-дог Мексиканский",
        "description": "Острый хот-дог с халапеньо и сырным соусом",
        "composition": "Булка, сосиска, сырный соус, халапеньо, кукуруза",
        "weight": "260 г",
        "price": 310,
    },
    {
        "id": "hotdog-chili-queso",
        "category_id": "hotdogs",
        "name": "Хот-дог Чилли Кон-Кесо",
        "description": "Сытный хот-дог с мясным соусом чили и сыром",
        "composition": "Булка, сосиска, соус чили кон карне, сырный соус",
        "weight": "280 г",
        "price": 330,
    },
    {
        "id": "hotdog-classic",
        "category_id": "hotdogs",
        "name": "Хот-дог Классический",
        "description": "Проверенная классика в дорогу",
        "composition": "Булка, сосиска, кетчуп, горчица, свежий огурец",
        "weight": "220 г",
        "price": 250,
    },
    {
        "id": "hotdog-cheese",
        "category_id": "hotdogs",
        "name": "Хот-дог Сырный",
        "description": "Хот-дог с двойной порцией сыра",
        "composition": "Булка, сосиска, сырный соус, моцарелла",
        "weight": "250 г",
        "price": 290,
    },
    {
        "id": "fries",
        "category_id": "snacks",
        "name": "Картофель Фри",
        "description": "Хрустящий картофель фри",
        "composition": "Картофель, соль, специи",
        "weight": "150 г",
        "price": 190,
    },
    {
        "id": "potato-wedges",
        "category_id": "snacks",
        "name": "Картофель Дольки",
        "description": "Деревенский картофель дольками со специями",
        "composition": "Картофель, паприка, специи",
        "weight": "180 г",
        "price": 210,
    },
    {
        "id": "nuggets",
        "category_id": "snacks",
        "name": "Наггетсы",
        "description": "Куриные наггетсы в хрустящей панировке",
        "composition": "Куриное филе, панировка, специи",
        "weight": "160 г",
        "price": 260,
    },
    {
        "id": "onion-rings",
        "category_id": "snacks",
        "name": "Луковые Кольца",
        "description": "Хрустящие луковые кольца в кляре",
        "composition": "Лук, кляр, панировка",
        "weight": "150 г",
        "price": 220,
    },
    {
        "id": "cheese-sticks",
        "category_id": "snacks",
        "name": "Сырные Палочки",
        "description": "Тающая моцарелла в хрустящей панировке",
        "composition": "Сыр моцарелла, панировка",
        "weight": "150 г",
        "price": 280,
    },
    {
        "id": "sauce-cheese",
        "category_id": "sauces",
        "name": "Сырный",
        "description": "Нежный сливочно-сырный соус",
        "composition": "Сыр, сливки, специи",
        "weight": "30 г",
        "price": 60,
    },
    {
        "id": "sauce-garlic",
        "category_id": "sauces",
        "name": "Чесночный",
        "description": "Ароматный чесночный соус",
        "composition": "Чеснок, майонез, специи",
        "weight": "30 г",
        "price": 50,
    },
    {
        "id": "sauce-bbq",
        "category_id": "sauces",
        "name": "Барбекю",
        "description": "Сладковато-дымный соус барбекю",
        "composition": "Томаты, специи, дым",
        "weight": "30 г",
        "price": 50,
    },
    {
        "id": "sauce-ketchup",
        "category_id": "sauces",
        "name": "Кетчуп",
        "description": "Классический томатный кетчуп",
        "composition": "Томаты, специи",
        "weight": "30 г",
        "price": 40,
    },
]

DEFAULT_NOTIFY_EMAIL = "Bigmadmuffin@yandex.ru"
